version: '3.8'

services:
  currency-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPEN_EXCHANGE_RATES_API_KEY=${OPEN_EXCHANGE_RATES_API_KEY}
    env_file:
      - .env.local
    restart: unless-stopped
